name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.15.4
          - 18.x
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: Run tests
        uses: williamhaw/setup-wiremock-action@v0.1.2
        id: setup-wiremock
        with:
          mappings: ${{ github.workspace }}/wiremock/mappings
          files: ${{ github.workspace }}/wiremock/__files
          command: 'npm run test:coverage'
